services:
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - 80:80
      - 81:81  # minio
    depends_on:
      - fastapi
      - minio
    links:
      - fastapi
      - minio
    networks:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  fastapi:
    build:
      context: .
      dockerfile: FastAPIDockerfile
    restart: on-failure
    depends_on:
      - minio
    ports:
      - '8000:8000'
    links:
      - minio
    networks:
      - app

  minio:
    image: minio/minio
    volumes:
      - ./media_minio:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'MINIOUSER'
      MINIO_ROOT_PASSWORD: 'MINIOPASSWORD'
    networks:
      - app


networks:
  app:
volumes:
  minio:
    driver: local